gitlab-runner:
  replicas: 1
  rbac:
    create: true
    podSecurityPolicy:
      enabled: true

  runners:
    config: |
      [[runners]]
        environment = ["container=docker"]
        [runners.kubernetes]
          image = "ubuntu:20.04"
          poll_timeout = 600
          helper_image_flavor = "ubuntu"

  runnerRegistrationToken: changeme
  gitlabUrl: https://gitlab.com
  logLevel: "debug"
